### ISSUE TITLE
missing RBAC for yugabyte CRDs in the created Service account

### ISSUE THREAD

**Issue by kaplan-michael** [yugabyte/yugabyte-k8s-operator#6]
**Describe the bug**

**To Reproduce**
Install via helm on OCP/OKD

Operator fails to construct a kube client due to missing RBAC config for yugabyte crds.
```bash
2024-05-14T01:00:48.389Z  [[31merror[0m]  KubernetesOperator.java:268 [Thread-11] com.yugabyte.yw.common.operator.KubernetesOperator Kubernetes Client Exception : 
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1:443/apis/operator.yugabyte.io/v1alpha1/ybuniverses?resourceVersion=0. Message: ybuniverses.operator.yugabyte.io is forbidden: User "system:serviceaccount:yugabyte-operator:yugabyte-operator" cannot list resource "ybuniverses" in API group "operator.yugabyte.io" at the cluster scope. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=operator.yugabyte.io, kind=ybuniverses, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ybuniverses.operator.yugabyte.io is forbidden: User "system:serviceaccount:yugabyte-operator:yugabyte-operator" cannot list resource "ybuniverses" in API group "operator.yugabyte.io" at the cluster scope, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:640)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:589)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:549)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:140)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpAsyncBody.doConsume(OkHttpClientImpl.java:137)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:174)
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:185)
		at io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer.run(DefaultSharedIndexInformer.java:171)
		at com.yugabyte.yw.common.operator.YBInformerFactory.getSharedIndexInformer(YBInformerFactory.java:55)
		at com.yugabyte.yw.common.operator.YBUniverseReconciler.<init>(YBUniverseReconciler.java:153)
		at com.yugabyte.yw.common.operator.YBUniverseReconciler.<init>(YBUniverseReconciler.java:121)
		at com.yugabyte.yw.common.operator.YBReconcilerFactory.getYBUniverseReconciler(YBReconcilerFactory.java:27)
		at com.yugabyte.yw.common.operator.KubernetesOperator.lambda$init$0(KubernetesOperator.java:212)
		... 1 common frames omitted
2024-05-14T01:00:48.390Z  [[31merror[0m]  KubernetesOperator.java:277 [Thread-11] com.yugabyte.yw.common.operator.KubernetesOperator Error
java.lang.RuntimeException: Operator Initialization Failed to construct a kubernetes client
	at com.yugabyte.yw.common.operator.KubernetesOperator.lambda$init$0(KubernetesOperator.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)
2024-05-14T01:00:48.390Z  [[31merror[0m]  KubernetesOperator.java:288 [Thread-11] com.yugabyte.yw.common.operator.KubernetesOperator Kubernetes operator thread failed
java.lang.RuntimeException: Operator Initialization Failed
	at com.yugabyte.yw.common.operator.KubernetesOperator.lambda$init$0(KubernetesOperator.java:278)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
this causes helm to fail due to timeout.
**Expected behavior**
operator is able to build a client and not CrashLoop

**Comment by amannijhawan** [comment]
@kaplan-michael Thanks for filing this, we will take a look at this issue and get back to you.

**Comment by amannijhawan** [comment]
@kaplan-michael, can you please share the kubectl/oc version details for this issue.

**Comment by kaplan-michael** [comment]
@amannijhawan 
here you go
``` bash
Client Version: 4.15.0-0.okd-2024-03-10-010116
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: 4.15.0-0.okd-2024-03-10-010116
Kubernetes Version: v1.28.2-3598+6e2789bbd58938-dirty
```

**Comment by amannijhawan** [comment]
```
2024-05-14T01:00:48.389Z  [�[31merror�[0m]  KubernetesOperator.java:268 [Thread-11] com.yugabyte.yw.common.operator.KubernetesOperator Kubernetes Client Exception : 
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1:443/apis/operator.yugabyte.io/v1alpha1/ybuniverses?resourceVersion=0. Message: ybuniverses.operator.yugabyte.io is forbidden: User "system:serviceaccount:yugabyte-operator:yugabyte-operator" cannot list resource "ybuniverses" in API group "operator.yugabyte.io" at the cluster scope. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=operator.yugabyte.io, kind=ybuniverses, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ybuniverses.operator.yugabyte.io is forbidden: User "system:serviceaccount:yugabyte-operator:yugabyte-operator" cannot list resource "ybuniverses" in API group "operator.yugabyte.io" at the cluster scope, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
```
@kaplan-michael 
From the above stacktrace it could be an rbac related issue, by any chance are you using rbac.create=false during the deployment, if so we will need to give the yb-operator  service account permissions to all resources in operatator.yugabyte.io apigroup.

Here is the link  for the parts of template that describes the rbac rules we use to deploy the template. 
https://github.com/yugabyte/yugabyte-k8s-operator/blob/main/chart/templates/rbac.yaml#L37

**Comment by amannijhawan** [comment]
Debugged this with @kaplan-michael  last week
The issue is ocpCompatibility is enabled, we disable create_rbac features.
